### ISSUE TITLE
Login page with username and password credentials.

### ISSUE THREAD

**Issue by nayana9823** [ElsaSusan98/FurryFriendFinder#10]

**Comment by ambilypremkumar** [comment]
login and register page are meant to be seperate pages

**Comment by ElsaSusan98** [comment]
Configuring the basic setup for login and register

**Comment by ElsaSusan98** [comment]
i am facing some issues with docker composer. docker is getting stuck

**Comment by ambilypremkumar** [comment]
Login page layout and design created

**Comment by ElsaSusan98** [comment]
Login page backend connection completed already
