### ISSUE TITLE
Adding sample data to data base

### ISSUE THREAD

**Issue by Ram2825** [ElsaSusan98/FurryFriendFinder#20]

**Comment by dvd777** [comment]
have you added any data

**Comment by Ram2825** [comment]
sample data was added to database!@_@!

**Comment by ElsaSusan98** [comment]
@Ram2825  Can you update the table with more data

**Comment by Ram2825** [comment]
@ElsaSusan98 I will upload extra data to data base

**Comment by ambilypremkumar** [comment]
already added sample data

**Comment by Ram2825** [comment]
Adding more entities in database.
