### ISSUE TITLE
register page for user

### ISSUE THREAD

**Issue by ambilypremkumar** [ElsaSusan98/FurryFriendFinder#24]
register page for user including all the essential fields

**Comment by ElsaSusan98** [comment]
created register page using pug?

**Comment by ElsaSusan98** [comment]
Register page and login page data fetching and authentication :inprogress

**Comment by ElsaSusan98** [comment]
Login authentication successfull

**Comment by ElsaSusan98** [comment]
Registration authentication from backend finished already and pushed to the main branch
