### ISSUE TITLE
About us page

### ISSUE THREAD

**Issue by dvd777** [ElsaSusan98/FurryFriendFinder#25]

**Comment by dvd777** [comment]
started to develop the page

**Comment by ambilypremkumar** [comment]
What is the status now?

**Comment by dvd777** [comment]
almost completed

**Comment by ambilypremkumar** [comment]
have done the front end side of about us page completly as per wireframe and pushed to git . kindly go through the page

**Comment by ambilypremkumar** [comment]
updated some allignment in aboutus page

**Comment by ElsaSusan98** [comment]
Finish the  style correctness in aboutus page @ambilypremkumar

**Comment by ambilypremkumar** [comment]
it is being done . will update further progress.

**Comment by ambilypremkumar** [comment]
already completed.
